languageCode = "en"
languageName = "English"
weight = 1
title = "Advance into Cloud Native"
disabled = false
contentDir = "content/en"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/logo.webp"
  # secondaryLogo = "PATH"
  description = "Advance into Cloud Native: A specialized blog diving into container technology, Kubernetes, Istio, DevOps practices, Prometheus monitoring, Envoy, Golang development, and trends in cloud-native architecture and microservices."
  # copyright = "Copy, _right?_ :thinking_face:"
  [params.article]
    editURL = "https://github.com/smallersoup/blog/tree/main/content/en"

  [[params.slideImages]]
    imgAddress = "https://socialify.git.ci/labring/sealos/image?description=1&descriptionEditable=a%20cloud%20operating%20system%20distribution%20based%20on%20the%20Kubernetes%20kernel.&font=Raleway&forks=1&logo=https%3A%2F%2Fcdn.jsdelivr.net%2Fgh%2Flabring%2Fsealos%40main%2Fdocs%2Fwebsite%2Fstatic%2Ficons%2Flogo.svg&name=1&owner=1&pattern=Brick%20Wall&stargazers=1&theme=Light"
    linkAddress = "https://github.com/labring/sealos"
    linkEvent = "Sealos"
  
  [[params.slideImages]]
    imgAddress = "https://socialify.git.ci/labring/fastgpt/image?description=1&descriptionEditable=a%20knowledge-based%20platform%20built%20on%20the%20LLM,%20offers%20out-of-the-box%20data%20processing%20and%20workflow%20orchestration%20through%20Flow%20visualization.&font=Raleway&forks=1&logo=https%3A%2F%2Fcdn.jsdelivr.net%2Fgh%2Flabring%2FFastGPT%40main%2F.github%2Fimgs%2Flogo.svg&name=1&pattern=Brick%20Wall&stargazers=1&theme=Light"
    linkAddress = "https://cloud.fastgpt.in/?inviterId=64215e9914d068bf840141d0"
    linkEvent = "FastGPT"
  
  [[params.slideImages]]
    imgAddress = "https://socialify.git.ci/labring/laf/image?description=1&descriptionEditable=Laf%20is%20a%20serverless%20platform%20integrating%20functions,%20databases%20and%20storage.%20Publish%20online%20anytime,%20anywhere.&font=Raleway&forks=1&logo=https%3A%2F%2Fcdn.jsdelivr.net%2Fgh%2Fsmallersoup%2Fimghosting-test%40main%2FuPic%2F2023-11-13-11-33-rI41Bu.svg&name=1&pattern=Brick%20Wall&stargazers=1&theme=Light"
    linkAddress = "https://github.com/labring/laf"
    linkEvent = "Laf"

  [params.author]
    name = "AndyLee8866"
    image = "img/avatar.jpeg"
    headline = "Cloud Native Lover ☸️, Blogger..."
    bio = "Cloud Native Lover ☸️, Blogger..."
    links = [
      { rss = "/index.xml" },
      # { x-twitter = "https://x.com/andylee8866" },
      { wechat = "/img/wechat-qr-code.jpg" },
      { github = "https://github.com/smallersoup" },
    ]