languageCode = "zh-cn"
languageName = "简体中文"
weight = 1
title = "进击云原生"
contentDir = "content/zh-cn"

[params]
  displayName = "中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006年1月2日"
  logo = "img/logo.webp"
  # secondaryLogo = "PATH"
  description = "进击云原生：深入探索容器技术、Kubernetes、Istio、DevOps 实践、Prometheus 监控、Envoy、Golang 开发以及云原生架构和微服务趋势的专业博客。"
  # copyright = "Copy, _right?_ :thinking_face:"
  [params.article]
    editURL = "https://github.com/smallersoup/blog/tree/main/content/zh-cn"

  [params.author]
    name = "小碗汤"
    image = "img/avatar.jpeg"
    headline = "云原生搬砖师"
    bio = "云原生搬砖师"
    links = [
      { rss = "/index.xml" },
      # { x-twitter = "https://x.com/andylee8866" },
      { wechat = "https://images.kubeinfo.cn/uPic/tmpm1ykjt96.webp" },
      { github = "https://github.com/smallersoup" },
    ]